version: '3'
services:
  movies:
    image: sandhyakrao/projectmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
 train:
   image: sandhyakrao/projecttrain:latest
   ports:
     - "82:80"
   deploy:
     replicas: 3
 dth:
   image: sandhyakrao/projectdth:latest
   ports:
     - "83:80"
   deploy:
     replicas: 3
 recharge:
   image: sandhyakrao/projectrecharge:latest
   ports:
     - "84:80"
   deploy:
     replicas: 3
   
